/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SasGyula(SZF_2023_20
 */
public class Ajtok extends javax.swing.JFrame {

    /**
     * Creates new form Ajtok
     */
    public Ajtok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajto2 = new javax.swing.JLabel();
        ajto3 = new javax.swing.JLabel();
        ajto1 = new javax.swing.JLabel();
        felfedesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ajto2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SasGyula(SZF_2023_20\\Documents\\NetBeansProjects\\Ajto\\kepek\\letöltés.png")); // NOI18N

        ajto3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SasGyula(SZF_2023_20\\Documents\\NetBeansProjects\\Ajto\\kepek\\letöltés.png")); // NOI18N

        ajto1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SasGyula(SZF_2023_20\\Documents\\NetBeansProjects\\Ajto\\kepek\\letöltés.png")); // NOI18N

        felfedesBtn.setText("Felfedés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(ajto1)
                .addGap(120, 120, 120)
                .addComponent(ajto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(ajto3)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(felfedesBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajto1)
                    .addComponent(ajto3)
                    .addComponent(ajto2))
                .addGap(18, 18, 18)
                .addComponent(felfedesBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajtok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajtok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajtok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajtok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajtok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajto1;
    private javax.swing.JLabel ajto2;
    private javax.swing.JLabel ajto3;
    private javax.swing.JButton felfedesBtn;
    // End of variables declaration//GEN-END:variables
}
